rails-api/config/routes.rb
Rails.application.routes.draw do
  resources :orders
  get 'ping', to: 'health_check#ping'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :shops do
    resources :meals, only: [:new, :create, :edit, :update, :destroy]
  end
  resources :meals, only: [:index, :show]
  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }
  devise_scope :user do
    get 'users/sign_in', :to => 'devise/sessions#new', :as => :new_user_session
    delete 'users/sign_out', :to => 'devise/sessions#destroy', :as => :destroy_user_session
  end
  root to: 'meals#index'
end

rails-api/app/models/shop.rb
class Shop < ApplicationRecord
  belongs_to :user, required: true
  has_many :meals, :dependent => :destroy
  validates :name, presence: true, uniqueness: true
  validates :user, presence: true

  def orders
    orders = []
    self.meals.each do |meal|
      orders.concat meal.orders
    end
    return orders
  end

  def active_orders
    orders = self.orders.reject do |order|
      !order.active?
    end
    return orders
  end
end

rails-api/app/controllers/shops_controller.rb
class ShopsController < ApplicationController
  before_action :set_shop, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  load_and_authorize_resource
  rescue_from CanCan::AccessDenied do |exception|
    respond_to do |format|
      format.json { head :forbidden }
      format.html { redirect_to meals_path, :alert => exception.message }
    end
  end
  # GET /shops
  # GET /shops.json
  def index
    @shops = current_user.shops.all
  end

  # GET /shops/1
  # GET /shops/1.json
  def show
    @meals = @shop.meals.all
  end

  # GET /shops/new
  def new
    @shop = Shop.new
  end

  # GET /shops/1/edit
  def edit
    @meals = @shop.meals.all
  end

  # POST /shops
  # POST /shops.json
  def create
    current_params = shop_params
    current_params[:user] = current_user
    @shop = Shop.new(current_params)

    respond_to do |format|
      if @shop.save
        current_user.add_role Role.find_by_name('shop_owner')
        current_user.save
        format.html { redirect_to @shop, notice: 'Shop was successfully created.' }
        format.json { render :show, status: :created, location: @shop }
      else
        format.html { render :new }
        format.json { render json: @shop.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /shops/1
  # PATCH/PUT /shops/1.json
  def update
    respond_to do |format|
      if @shop.update(shop_params)
        format.html { redirect_to @shop, notice: 'Shop was successfully updated.' }
        format.json { render :show, status: :ok, location: @shop }
      else
        format.html { render :edit }
        format.json { render json: @shop.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /shops/1
  # DELETE /shops/1.json
  def destroy
    @shop.destroy
    respond_to do |format|
      format.html { redirect_to shops_url, notice: 'Shop was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_shop
      @shop = Shop.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def shop_params
      params.require(:shop).permit(:name, :location, :description, :user_id)
    end
end

rails-api/app/views/shops/_form.html.erb
<div class="text-center" style="padding:50px 0">
  <%= form_with(model: shop, local: true, class: "form-horizontal denser") do |f| %>
    <% if shop.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(shop.errors.count, "error") %> prohibited this shop from being saved:</h2>

        <ul>
        <% shop.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <fieldset>
      <div class="form-group control-group string_type">
        <%= f.text_field :name, class: "col-sm-10 controls", id: "lg_username", placeholder: :name %>
      </div>
      <div class="form-group control-group string_type">
        <%= f.text_field :location, class: "col-sm-10 controls", placeholder: :location %>
      </div>
      <div class="form-group control-group string_type">
        <%= f.text_area :description, class: "col-sm-10 controls", placeholder: :description %>
      </div>
    </fieldset>
    <div class="form-group form-actions">
      <%= f.submit class: "btn btn-primary" %>
    </div>
  <% end %>
</div>

rails-api/app/views/shops/edit.html.erb
<div class="page-header text-center mt-5">
  <h1>Edit Shop</h1>
</div>
<%= render 'form', shop: @shop %>

<div class="page-header text-center mt-5">
  <h3>Shop Meals</h3>
</div>

<table class="table table-condensed table-striped">
  <thead>
    <tr>
      <th class="header pjax">Name</th>
      <th class="header pjax">Type</th>
      <th class="header pjax">Price</th>
      <th class="header pjax">Description</th>
      <th  class="header pjax" colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @meals.each do |meal| %>
      <tr>
        <td><%= meal.name %></td>
        <td><%= meal.meal_type %></td>
        <td><%= meal.price %></td>
        <td><%= meal.description %></td>
        <td class="last links">
          <ul class="list-inline">
            <li title="Edit" rel="tooltip" class="icon list-inline-item">
              <%= link_to fa_icon("pencil"), edit_shop_meal_path(@shop, meal), class: "pjax" %>
            </li>
            <li title="Delete" rel="tooltip" class="icon list-inline-item">
              <%= link_to fa_icon("remove"), shop_meal_path(@shop, meal), method: :delete, data: { confirm: 'Are you sure?' }, class: "pjax" %>
            </li>
          </ul>
        </td>
      </tr>
    <% end %>
    <tr><%= link_to fa_icon("plus-circle", text: "New Meal"), new_shop_meal_path(@shop), class: "pjax" %></tr>
  </tbody>
</table>

<%= link_to fa_icon("arrow-circle-left", text: "Back"), shops_path(@shop), class: "pjax mb-5" %>

rails-api/app/views/shops/index.html.erb
<div class="page-header text-center mt-5">
  <h1>Shops</h1>
</div>

<table class="table table-condensed table-striped">
  <thead>
    <tr>
      <th class="header pjax">Name</th>
      <th class="header pjax">Location</th>
      <th class="header pjax">Description</th>
      <th class="header pjax" colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @shops.each do |shop| %>
      <tr>
        <td><%= shop.name %></td>
        <td><%= shop.location %></td>
        <td><%= shop.description %></td>
        <td class="last links">
          <ul class="list-inline">
            <li title="Edit" rel="tooltip" class="icon list-inline-item">
              <%= link_to fa_icon("pencil"), edit_shop_path(shop), class: "pjax", id: "edit-link" %>
            </li>
            <li title="Delete" rel="tooltip" class="icon list-inline-item">
              <%= link_to fa_icon("remove"), shop, method: :delete, data: { confirm: 'Are you sure?' }, class: "pjax", id: "delete-link" %>
            </li>
          </ul>
        </td>
      </tr>
    <% end %>
    <tr><%= link_to fa_icon("plus-circle", text: "New Shop"), new_shop_path, class: "pjax" %></tr>
  </tbody>
</table>

<br>

<%= link_to fa_icon("arrow-circle-left", text: "Back"), root_path, class: "pjax mb-5" %>

rails-api/app/views/shops/new.html.erb
<h1>New Shop</h1>

<%= form_for @shop do |f| %>
  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :location %>
    <%= f.text_field :location %>
  </div>


  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

  <div class="actions">
    <%= f.submit "Create Shop" %>
  </div>
<% end %>

<%= link_to 'Back', shops_path %>

rails-api/app/views/shops/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @shop.name %>
</p>

<p>
  <strong>Location:</strong>
  <%= @shop.location %>
</p>

<p>
  <strong>Description:</strong>
  <%= @shop.description %>
</p>

<% if @meals.count > 0 %>
  <table>
    <thead>
      <tr>
        <th>Name</th>
        <th>Type</th>
        <th>Price</th>
        <th>Description</th>
        <th>Shop</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @meals.each do |meal| %>
        <tr>
          <td><%= meal.name %></td>
          <td><%= meal.meal_type %></td>
          <td><%= meal.price %></td>
          <td><%= meal.description %></td>
          <td><%= link_to 'Show', meal %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>

<%= link_to 'Edit', edit_shop_path(@shop) %> |
<%= link_to 'Back', shops_path %>