rails-api/config/routes.rb
Rails.application.routes.draw do
  resources :orders
  get 'ping', to: 'health_check#ping'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :shops do
    resources :meals, only: [:new, :create, :edit, :update, :destroy]
  end
  resources :meals, only: [:index, :show]
  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }
  devise_scope :user do
    get 'users/sign_in', :to => 'devise/sessions#new', :as => :new_user_session
    delete 'users/sign_out', :to => 'devise/sessions#destroy', :as => :destroy_user_session
  end
  root to: 'meals#index'
end

rails-api/app/models/meal.rb
class Meal < ApplicationRecord
  belongs_to :shop, required: true
  has_many :orders, :dependent => :destroy
  validates :name, presence: true, uniqueness: true
  validates :shop, presence: true
  has_one_attached :image
  validates :image, presence: true
end

rails-api/app/controllers/meals_controller.rb
class MealsController < ApplicationController
  before_action :set_meal, only: [:show, :edit, :update, :destroy]
  before_action :set_shop, only: [:new, :edit, :create, :update, :destroy]
  before_action :authenticate_user!

  load_and_authorize_resource
  rescue_from CanCan::AccessDenied do |exception|
    respond_to do |format|
      format.json { head :forbidden }
      format.html { redirect_to meals_path, :alert => exception.message }
    end
  end
  # GET /meals
  # GET /meals.json
  def index
    @meals = Meal.all
  end

  # GET /meals/1
  # GET /meals/1.json
  def show
  end

  # GET /meals/new
  def new
    @meal = Meal.new
  end

  # GET /meals/1/edit
  def edit
  end

  # POST /meals
  # POST /meals.json
  def create
    @meal = @shop.meals.new(meal_params)
    @meal.image.attach(params[:meal][:image])
    respond_to do |format|
      if @meal.save
        format.html { redirect_to edit_shop_meal_url(@shop, @meal), notice: 'Meal was successfully created.' }
        format.json { render :show, status: :created, location: @meal }
      else
        format.html { render :new, notice: 'Unable to create meal'}
        format.json { render json: @meal.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /meals/1
  # PATCH/PUT /meals/1.json
  def update
    respond_to do |format|
      if @meal.update(meal_params)
        flash[:notice] = 'Meal was successfully updated.'
        format.html { redirect_to edit_shop_meal_url(@shop, @meal) }
        format.json { render :index, status: :ok, location: @meal }
      else
        flash[:alert] = 'Cannot update meal.'
        format.html { render :edit, error: @meal.errors }
        format.json { render json: @meal.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /meals/1
  # DELETE /meals/1.json
  def destroy
    @meal.destroy
    respond_to do |format|
      format.html { redirect_to edit_shop_url(@shop), notice: 'Meal was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_meal
      @meal = Meal.find(params[:id])
    end

    def set_shop
      @shop = Shop.find(params[:shop_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def meal_params
      params.require(:meal).permit(:name, :description, :shop_id, :meal_type, :price)
    end
end

rails-api/app/views/meals/_form.html.erb
<%= form_with(model: meal, local: true) do |form| %>
  <% if meal.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(meal.errors.count, "error") %> prohibited this meal from being saved:</h2>

      <ul>
      <% meal.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :meal_type %>
    <%= form.text_field :meal_type %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description %>
  </div>

  <div class="field">
    <%= form.label :shop_id %>
    <%= form.text_field :shop_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

rails-api/app/views/meals/edit.html.erb
<div class="page-header text-center mt-5">
  <h1>Editing Meal</h1>
</div>
<div class="text-center">
  <% if @meal.image.attached? %>
    <%= image_tag @meal.image, class: "img-fluid rounded mx-auto d-block m-5" %>
  <% end %>
</div>

<div class="text-center" style="padding:50px 0">
	<!-- Main Form -->
  <%= form_for @meal, id: "login-form", class: "form-horizontal denser", url: shop_meal_url(@shop, @meal) do |f| %>
		<% if @meal.errors.any? %>
			<div id="error_explanation">
				<h2><%= pluralize(@meal.errors.count, "error") %> prohibited this meal from being saved:</h2>

				<ul>
				<% @meal.errors.full_messages.each do |message| %>
					<li><%= message %></li>
				<% end %>
				</ul>
			</div>
		<% end %>
		<fieldset>
			<div class="form-group control-group string_type">
        <%= f.text_field :name, class: "col-sm-10 controls", id: "lg_username", placeholder: :name %>
			</div>
			<div class="form-group control-group string_type">
        <%= f.text_field :meal_type, class: "col-sm-10 controls", id: "lg_password", placeholder: :meal_type %>
			</div>
			<div class="form-group control-group string_type">
        <%= f.text_area :description, class: "col-sm-10 controls", placeholder: :description %>
			</div>
			<div class="form-group control-group">
        <%= f.number_field :price, class: "col-sm-10 controls", placeholder: :price %>
			</div>
      <div class="form-group control-group">
        <%= f.label :image, class: "col-sm-2 control-label"%>
        <%= f.file_field(:image, class: "col-sm-10 controls") %>
			</div>
		</fieldset>
		<div class="form-group form-actions">
			<%= f.submit class: "btn btn-primary" %>
		</div>
	<% end %>
	<!-- end:Main Form -->
</div>

<%= link_to fa_icon("arrow-circle-left", text: "Back"), edit_shop_path(@shop), class: "pjax mb-5" %>

rails-api/app/views/meals/index.html.erb
<%= stylesheet_link_tag    'meals', media: 'all', 'data-turbolinks-track': 'reload' %>

<div class="page-header text-center mt-5">
  <h1>Meals</h1>
</div>

<div class="container">
  <div class="row">
    <% @meals.each do |meal| %>
      <div class="col-md-4 mt-3 mb-3">
        <div class="thumbnail">
          <div class="caption align-middle">
            <h4 class="mt-4"><%= meal.name %></h4>
            <p><%= meal.price %> Baht</p>
            <p>
              <%= link_to 'Show', meal, class: "label label-default", rel: "tooltip" %>
              <%= link_to 'Order', orders_path(order: {meal_id: meal}), :method=> :post, data: { confirm: 'Are you sure?' }, class: "label label-default", rel: "tooltip" %>
            </p>
          </div>
          <% if meal.image.attached? %>
            <%= image_tag meal.image, class: "rounded object-fit_cover" %>
          <% else %>
            <%= image_tag "https://via.placeholder.com/250", class: "rounded object-fit_cover" %>
          <% end %>
        </div>
        <p class="text-center"><%= meal.shop.name %></p>
      </div>
    <% end %>
  </div>
</div><!-- /.container -->

rails-api/app/views/meals/new.html.erb
<div class="page-header text-center mt-5">
  <h1>New Meal</h1>
</div>
<div class="text-center" style="padding:50px 0">
	<!-- Main Form -->
  <%= form_for @meal, id: "login-form", class: "form-horizontal denser", url: shop_meals_url(@shop, @meal) do |f| %>
		<% if @meal.errors.any? %>
			<div id="error_explanation">
				<h2><%= pluralize(@meal.errors.count, "error") %> prohibited this meal from being saved:</h2>

				<ul>
				<% @meal.errors.full_messages.each do |message| %>
					<li><%= message %></li>
				<% end %>
				</ul>
			</div>
		<% end %>
		<fieldset>
			<div class="form-group control-group string_type">
        <%= f.text_field :name, class: "col-sm-10 controls", id: "lg_username", placeholder: :name %>
			</div>
			<div class="form-group control-group string_type">
        <%= f.text_field :meal_type, class: "col-sm-10 controls", id: "lg_password", placeholder: :meal_type %>
			</div>
			<div class="form-group control-group string_type">
        <%= f.text_area :description, class: "col-sm-10 controls", placeholder: :description %>
			</div>
			<div class="form-group control-group">
        <%= f.number_field :price, class: "col-sm-10 controls", placeholder: :price %>
			</div>
      <div class="form-group control-group">
        <%= f.label :image, class: "col-sm-2 control-label"%>
        <%= f.file_field(:image, class: "col-sm-10 controls") %>
			</div>
		</fieldset>
		<div class="form-group form-actions">
			<%= f.submit class: "btn btn-primary" %>
		</div>
	<% end %>
	<!-- end:Main Form -->
</div>

<%= link_to 'Back', edit_shop_path(@shop) %>

rails-api/app/views/meals/show.html.erb
<p id="notice"><%= notice %></p>

<% if @meal.image.attached? %>
  <%= image_tag @meal.image, class: "img-fluid rounded mx-auto d-block" %>
<% end %>

<p>
  <strong>Name:</strong>
  <%= @meal.name %>
</p>

<p>
  <strong>Type:</strong>
  <%= @meal.meal_type %>
</p>

<p>
  <strong>Description:</strong>
  <%= @meal.description %>
</p>

<p>
  <strong>Price:</strong>
  <%= @meal.price %>
</p>

<%= link_to 'Back', meals_path %>