rails-api/config/routes.rb
Rails.application.routes.draw do
  resources :orders
  get 'ping', to: 'health_check#ping'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :shops do
    resources :meals, only: [:new, :create, :edit, :update, :destroy]
  end
  resources :meals, only: [:index, :show]
  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }
  devise_scope :user do
    get 'users/sign_in', :to => 'devise/sessions#new', :as => :new_user_session
    delete 'users/sign_out', :to => 'devise/sessions#destroy', :as => :destroy_user_session
  end
  root to: 'meals#index'
end

rails-api/app/models/order.rb
class Order < ApplicationRecord
  belongs_to :meal
  belongs_to :user

  enum order_status: [ :pending, :rejected, :preparing, :prepared, :served ]

  validates :user, presence: true
  validates :meal, presence: true
  validates :status, :inclusion => {:in => order_statuses}, on: :update

  before_create :add_default_status

  def add_default_status
    self.status = :pending
  end

  def active?
    !(self.status.eql? "rejected") && !(self.status.eql? "served")
  end
end

rails-api/app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: [:show, :edit, :update, :destroy]

  # GET /orders
  # GET /orders.json
  def index
    @orders = current_user.active_orders
  end

  # GET /orders/1
  # GET /orders/1.json
  def show
  end

  # GET /orders/new
  def new
    @order = Order.new
  end

  # GET /orders/1/edit
  def edit
  end

  # POST /orders
  # POST /orders.json
  def create
    @order = current_user.orders.new(order_params)

    respond_to do |format|
      if @order.save
        format.html { redirect_to orders_url, notice: 'Order was successfully created.' }
        format.json { render :show, status: :created, location: @order }
      else
        format.html { redirect_to meals_url, notice: 'Order was not successfully created.'  }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /orders/1
  # PATCH/PUT /orders/1.json
  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to orders_url, notice: "Order: #{@order.id} was successfully updated." }
        format.json { render :show, status: :ok, location: @order }
      else
        format.html { redirect_to orders_url, notice: "Order: #{@order.id} was not successfully updated." }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    @order.destroy
    respond_to do |format|
      format.html { redirect_to orders_url, notice: 'Order was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_params
      params.fetch(:order).permit(:meal_id, :status)
    end
end

rails-api/app/views/orders/_form.html.erb
<%= form_with(model: order, local: true) do |form| %>
  <% if order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(order.errors.count, "error") %> prohibited this order from being saved:</h2>

      <ul>
      <% order.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

rails-api/app/views/orders/edit.html.erb
<h1>Editing Order</h1>

<%= render 'form', order: @order %>

<%= link_to 'Show', @order %> |
<%= link_to 'Back', orders_path %>

rails-api/app/views/orders/index.html.erb
<div class="page-header text-center">
  <h1>Orders</h1>
</div>

<h3>My Orders</h3>
<table class="table table-condensed table-striped">
  <thead>
    <tr>
      <th class="header pjax">Order ID</th>
      <th class="header pjax">Meal Name</th>
      <th class="header pjax">Status</th>
      <th class="header pjax" colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @orders.each do |order| %>
      <tr>
        <td>order: <%= order.id %></td>
        <td><%= order.meal.name %></td>
        <% case order.status %>
        <% when "pending" %>
          <td class="text-warning">
        <% when "preparing" %>
          <td class="text-primary">
        <% else %>
          <td class="text-success">
        <% end %>
          <%= order.status.capitalize %>
        </td>
        <% if order.status.eql? "prepared" %>
          <td>
            <ul class="list-inline">
              <li title="Receive" rel="tooltip" class="icon list-inline-item">
                <%= link_to fa_icon("check-circle", text: "receive"), order_path(id: order.id, order: {meal_id: order.meal_id, status: "served"}), method: "patch", class: "pjax text-success", id: "receive-link" %>
              </li>
            </ul>
          </td>
        <% else %>
          <td></td>
        <% end %>
        <td class="last links">
          <ul class="list-inline">
            <li title="Show" rel="tooltip" class="icon list-inline-item">
              <%= link_to fa_icon("info", text: "info"), order, class: "pjax" %>
            </li>
          </ul>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<% current_user.shops.each do |shop| %>
  <h3><%= shop.name  %> orders</h3>
  <table class="table table-condensed table-striped">
    <thead>
      <tr>
        <th class="header pjax">Order ID</th>
        <th class="header pjax">Meal Name</th>
        <th class="header pjax">Status</th>
        <th class="header pjax" colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% shop.active_orders.each do |order| %>
        <tr>
          <td>order: <%= order.id %></td>
          <td><%= order.meal.name %></td>
          <% case order.status %>
          <% when "pending" %>
            <td class="text-warning">
          <% when "preparing" %>
            <td class="text-primary">
          <% else %>
            <td class="text-success">
          <% end %>
            <%= order.status.capitalize %>
          </td>
          <td class="links">
            <ul class="list-inline">
              <% if order.status.eql? "pending" %>
                <li title="Accept", rel="tooltip" class="icon list-inline-item">
                  <%= link_to fa_icon("check", text: "accept"), order_path(id: order.id, order: {meal_id: order.meal_id, status: "preparing"}), method: "patch", class: "pjax text-primary", id: "accept-link" %>
                </li>
                <li title="Reject" rel="tooltip" class="icon list-inline-item">
                  <%= link_to fa_icon("ban", text: "reject"), order_path(id: order.id, order: {meal_id: order.meal_id, status: "rejected"}), method: "patch", class: "pjax text-danger", id: "reject-link" %>
                </li>
              <% elsif order.status.eql? "preparing" %>
                <li title="Finish" rel="tooltip" class="icon list-inline-item">
                  <%= link_to fa_icon("check-circle", text: "finish"), order_path(id: order.id, order: {meal_id: order.meal_id, status: "prepared"}), method: "patch", class: "pjax text-success",  id: "finish-link" %>
                </li>
              <% else %>
                <li></li>
              <% end %>
            </ul>
          </td>
          <td class="last links">
            <ul class="list-inline">
              <li title="Show" rel="tooltip" class="icon list-inline-item">
                <%= link_to fa_icon("info", text: "info"), order, class: "pjax" %>
              </li>
            </ul>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>

<%= link_to fa_icon("arrow-circle-left", text: "Back"), root_path, class: "pjax mb-5" %>

rails-api/app/views/orders/new.html.erb
<h1>New Order</h1>

<%= render 'form', order: @order %>

<%= link_to 'Back', orders_path %>

rails-api/app/views/orders/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_order_path(@order) %> |
<%= link_to 'Back', orders_path %>