rails-api/config/routes.rb
Rails.application.routes.draw do
  resources :orders
  get 'ping', to: 'health_check#ping'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :shops do
    resources :meals, only: [:new, :create, :edit, :update, :destroy]
  end
  resources :meals, only: [:index, :show]
  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }
  devise_scope :user do
    get 'users/sign_in', :to => 'devise/sessions#new', :as => :new_user_session
    delete 'users/sign_out', :to => 'devise/sessions#destroy', :as => :destroy_user_session
  end
  root to: 'meals#index'
end

rails-api/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MealAgent</title>
    <meta charset="UTF-8">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <!-- Fixed navbar -->
    <nav class="navbar navbar-default navbar-expand-xl navbar-light navbar-fixed-top">
      <div class="container-fluid">
        <div class="navbar-header d-flex">
          <%= link_to fa_icon("list-alt", text: "Meal Agent"), root_path, class: "navbar-brand" %>
      		<button type="button" data-target="#navbarCollapse" data-toggle="collapse" class="navbar-toggle navbar-toggler ml-auto">
      			<span class="navbar-toggler-icon"></span>
      			<span class="icon-bar"></span>
      			<span class="icon-bar"></span>
      			<span class="icon-bar"></span>
      		</button>
      	</div>
      	<!-- Collection of nav links, forms, and other content for toggling -->
      	<div id="navbarCollapse" class="collapse navbar-collapse justify-content-start">
      		<ul class="nav navbar-nav">
            <li class="nav-item"><%= link_to fa_icon("shopping-cart", text: "Meals"), meals_path, class: "nav-link" %></li>
            <li class="nav-item">
              <%= link_to orders_path, class: "nav-link", role: "presentation" do %>
                <%= fa_icon("book") %>Orders<span class="badge"><%= cookies[:num_order_change] %></span>
              <% end %>
            </li>
          </ul>
          <% if user_signed_in? %>
        		<ul class="nav navbar-nav navbar-right ml-auto">
        			<li class="nav-item dropdown">
        				<a href="#" data-toggle="dropdown" class="nav-link dropdown-toggle user-action"><%= image_tag current_user.image, class: "avatar" %> <%= current_user.name %> <b class="caret"></b></a>
                <ul class="dropdown-menu">
                  <li><% if current_user.shop_owner? %>
                    <%= link_to fa_icon("shopping-bag", text: "My Shops"), shops_path, class: "dropdown-item" %>
                  <% else %>
                    <%= link_to fa_icon("shopping-bag", text: "New shop"), new_shop_path, class: "dropdown-item" %>
                  <% end %></li>
        					<li class="divider dropdown-divider"></li>
                  <li><%= link_to fa_icon("power-off", text: "Logout"), destroy_user_session_path, method: :delete, class: "dropdown-item" %></li>
        				</ul>
        			</li>
        		</ul>
          <% else %>
            <ul class="nav navbar-nav navbar-right ml-auto">
              <li class="nav-item dropdown">
                <%= link_to "Sign in with Google", user_google_oauth2_omniauth_authorize_path, class: "nav-link user-action" %>
        			</li>
            </ul>
          <% end %>
      	</div>
      </div>
    </nav>
    <% if flash[:error] %>
      <div class="alert alert-danger alert-dismissible" role="alert">
        <p><%= flash[:error] %></p>
      </div>
    <% end %>
    <% if flash[:alert] %>
      <div class="alert alert-warning alert-dismissible" role="alert">
        <p><%= flash[:alert] %></p>
      </div>
    <% end %>
    <% if flash[:notice] %>
      <div class="alert alert-info alert-dismissible" role="alert">
        <p><%= flash[:notice] %></p>
      </div>
    <% end %>

    <div id="container" class="container">
      <%= yield %>
    </div>

  </body>
</html>